In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import os.path as path

In [4]:
df1 = pd.read_csv('./data/analyze/method1/accuracy.csv', index_col=0)
df2 = pd.read_csv('./data/analyze/method2/accuracy.csv', index_col=0)
df3 = pd.read_csv('./data/analyze/new_data_method1/accuracy.csv', index_col=0)
df4 = pd.read_csv('./data/analyze/new_data_method2/accuracy.csv', index_col=0)
df5 = pd.read_csv('./data/analyze/deberta_method2/accuracy.csv', index_col=0)

df1['method'] = 1
df2['method'] = 2
df_full = pd.concat([df1, df2], ignore_index=True)

df3['method'] = 1
df4['method'] = 2
df_full_new = pd.concat([df3, df4], ignore_index=True)

df5['method'] = 2

In [5]:
df = df5

In [7]:
df[(df['model'] == 'base_model') & (df['method'] == 2)].sort_values(by=['f1_score'], ascending=False)

        model  level  threshold  method  accuracy  f1_score  recall  precision
8  base_model    NaN       0.90       2   0.66970  0.197522  0.4065   0.130456
7  base_model    NaN       0.85       2   0.25470  0.183770  0.8390   0.103185
6  base_model    NaN       0.80       2   0.13070  0.183142  0.9745   0.101068
5  base_model    NaN       0.75       2   0.10745  0.182010  0.9930   0.100187
4  base_model    NaN       0.70       2   0.10475  0.181785  0.9945   0.100035
3  base_model    NaN       0.65       2   0.10430  0.181710  0.9945   0.099990
0  base_model    NaN       0.50       2   0.10425  0.181702  0.9945   0.099985
1  base_model    NaN       0.55       2   0.10425  0.181702  0.9945   0.099985
2  base_model    NaN       0.60       2   0.10425  0.181702  0.9945   0.099985